apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploy-resume-manager.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: deploy-resume-manager
  template:
    metadata:
      labels:
        app: deploy-resume-manager
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
