apiVersion: v1
kind: Service
metadata:
  name: deploy-resume-manager
spec:
  type: NodePort
  selector:
    app: deploy-resume-manager
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
